# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(496, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 35))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        Form.setStyleSheet("\n"
"QWidget#Form {\n"
"    border-image: url(:/register/images/register.jpg);\n"
"}\n"
"\n"
"")
        self.main_menue_btn = QtWidgets.QPushButton(Form)
        self.main_menue_btn.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.main_menue_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(11, 1, 126)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(0, 85, 127);\n"
"}")
        self.main_menue_btn.setCheckable(True)
        self.main_menue_btn.setObjectName("main_menue_btn")
        self.exit_menue_btn = QtWidgets.QPushButton(Form)
        self.exit_menue_btn.setGeometry(QtCore.QRect(10, 100, 50, 50))
        self.exit_menue_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(11, 1, 126)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(0, 85, 127);\n"
"}")
        self.exit_menue_btn.setCheckable(False)
        self.exit_menue_btn.setObjectName("exit_menue_btn")
        self.reset_menue_btn = QtWidgets.QPushButton(Form)
        self.reset_menue_btn.setGeometry(QtCore.QRect(70, 70, 50, 50))
        self.reset_menue_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(11, 1, 126)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(0, 85, 127);\n"
"}")
        self.reset_menue_btn.setCheckable(False)
        self.reset_menue_btn.setObjectName("reset_menue_btn")
        self.about_menue_btn = QtWidgets.QPushButton(Form)
        self.about_menue_btn.setGeometry(QtCore.QRect(80, 10, 50, 50))
        self.about_menue_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 4px double rgb(11, 1, 126)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(0, 85, 127);\n"
"}")
        self.about_menue_btn.setCheckable(False)
        self.about_menue_btn.setObjectName("about_menue_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 170, 261, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 10pt \"黑体\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_le.setMinimumSize(QtCore.QSize(0, 30))
        self.password_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(197, 197, 197);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;;")
        self.password_le.setClearButtonEnabled(True)
        self.password_le.setObjectName("password_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_le)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.confirm_pwd_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirm_pwd_le.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm_pwd_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(197, 197, 197);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;;")
        self.confirm_pwd_le.setClearButtonEnabled(True)
        self.confirm_pwd_le.setObjectName("confirm_pwd_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_pwd_le)
        self.account_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.account_le.setMinimumSize(QtCore.QSize(0, 30))
        self.account_le.setStyleSheet("background-color: transparent;\n"
"color: rgb(197, 197, 197);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;;")
        self.account_le.setClearButtonEnabled(True)
        self.account_le.setObjectName("account_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_le)
        self.register_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.register_btn.setEnabled(False)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.register_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(20, 47, 66);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(185, 231, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(4, 14, 148);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.register_btn)
        self.exit_menue_btn.raise_()
        self.reset_menue_btn.raise_()
        self.about_menue_btn.raise_()
        self.layoutWidget.raise_()
        self.main_menue_btn.raise_()

        self.retranslateUi(Form)
        self.main_menue_btn.clicked['bool'].connect(Form.show_hide_menue) # type: ignore
        self.about_menue_btn.clicked.connect(Form.about_lk) # type: ignore
        self.reset_menue_btn.clicked.connect(Form.reset) # type: ignore
        self.exit_menue_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.register_btn.clicked.connect(Form.check_reqister) # type: ignore
        self.account_le.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.password_le.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.confirm_pwd_le.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_menue_btn.setText(_translate("Form", "菜单"))
        self.exit_menue_btn.setText(_translate("Form", "退出"))
        self.reset_menue_btn.setText(_translate("Form", "重置"))
        self.about_menue_btn.setText(_translate("Form", "关于"))
        self.layoutWidget.setStyleSheet(_translate("Form", "color: rgb(225, 225, 225);\n"
"font: 10pt \"黑体\";"))
        self.label.setText(_translate("Form", "账   号:"))
        self.label_2.setStyleSheet(_translate("Form", "color: rgb(225, 225, 225);\n"
"font: 10pt \"黑体\";"))
        self.label_2.setText(_translate("Form", "密   码:"))
        self.label_3.setStyleSheet(_translate("Form", "color: rgb(225, 225, 225);\n"
"font: 10pt \"黑体\";"))
        self.label_3.setText(_translate("Form", "确认密码:"))
        self.register_btn.setText(_translate("Form", "注册"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
